parameters:
    widop_php_bb.user_manager.class: Widop\PhpBBBundle\Model\UserManager
    widop_php_bb.authentication_manager.class: Widop\PhpBBBundle\Model\AuthenticationManager

services:
    widop_php_bb.user_manager:
        class: %widop_php_bb.user_manager.class%
        arguments: [ %widop_php_bb.path%, @kernel ]

    widop_php_bb.authentication_manager:
        class: %widop_php_bb.authentication_manager.class%
        arguments: [ %widop_php_bb.path%, @kernel ]
